import { readFile, writeFile } from "node:fs/promises";
import { fileURLToPath } from "node:url";
import { dirname, resolve } from "node:path";

const scriptDir = dirname(fileURLToPath(import.meta.url));
const schemaPath = resolve(scriptDir, "../prisma/schema.prisma");
const outputPath = resolve(scriptDir, "../prisma/ERD.md");
const schema = await readFile(schemaPath, "utf8");
const models = [...schema.matchAll(/model\s+(\w+)\s*\{([\s\S]*?)^\}/gm)];
const modelNames = new Set(models.map(([, name]) => name));
const lines = ["# Database entity relationship diagram", "", "Generated from `schema.prisma` by `npm run db:erd`. Do not edit this file directly.", "", "```mermaid", "erDiagram"];
const relations = [];

for (const [, model, body] of models) {
  lines.push(`  ${model} {`);
  for (const rawLine of body.split("\n")) {
    const line = rawLine.trim();
    const field = line.match(/^(\w+)\s+([\w?\[\]]+)/);
    if (!field) continue;
    const [, fieldName, declaredType] = field;
    const target = declaredType.replace(/[?\[\]]/g, "");
    if (modelNames.has(target)) {
      if (/@relation\([^)]*fields:/.test(line)) {
        const fk = line.match(/fields:\s*\[(\w+)\]/)?.[1] ?? fieldName;
        const uniqueForeignKey = body.split("\n").some((candidate) => candidate.trim().startsWith(`${fk} `) && candidate.includes("@unique"));
        const optionalForeignKey = body.split("\n").some((candidate) => candidate.trim().startsWith(`${fk} `) && candidate.trim().split(/\s+/)[1]?.endsWith("?"));
        relations.push(`  ${target} ${optionalForeignKey ? "o|" : "||"}--o${uniqueForeignKey ? "|" : "{"} ${model} : "${fk}"`);
      }
      continue;
    }
    const type = target === "String" ? "string" : target === "Int" ? "int" : target === "Boolean" ? "boolean" : target === "DateTime" ? "datetime" : target === "Decimal" ? "decimal" : target === "Json" ? "json" : target.toLowerCase();
    const attrs = `${line.includes("@id") ? " PK" : ""}${line.includes("@unique") ? " UK" : ""}${line.includes("@default") ? " DEFAULT" : ""}`;
    lines.push(`    ${type} ${fieldName}${attrs}`);
  }
  lines.push("  }");
}
lines.push(...relations, "```", "");
await writeFile(outputPath, lines.join("\n"));
process.stdout.write(`Wrote ${outputPath} from ${models.length} Prisma models.\n`);
