/** Public API contract for the endpoints mounted in app.ts. Keep this in sync with route schemas. */
const jsonBody = { required: true, content: { "application/json": { schema: { type: "object", additionalProperties: true } } } };
const response = (description: string) => ({ description });
const operation = (summary: string, secured = false) => ({
  summary,
  ...(secured ? { security: [{ bearerAuth: [] }] } : {}),
  responses: { "200": response("Request completed"), "400": response("Invalid request"), "401": response("Authentication required"), "403": response("Insufficient permissions"), "404": response("Resource not found"), "500": response("Unexpected server error") },
});
const pathParam = (name: string) => ({ name, in: "path", required: true, schema: { type: "string", format: "uuid" } });

export const openApiSpec = {
  openapi: "3.0.3",
  info: { title: "Job Portal API", version: "1.0.0", description: "REST API for candidates, recruiters, company administrators, and platform administrators. Access tokens use Bearer authentication; refresh tokens are HTTP-only cookies." },
  servers: [{ url: "/", description: "Current API host" }],
  tags: ["Auth", "Companies", "Profiles", "Jobs", "Applications", "Interviews", "Notifications", "Admin", "Uploads"].map((name) => ({ name })),
  components: { securitySchemes: { bearerAuth: { type: "http", scheme: "bearer", bearerFormat: "JWT" } } },
  paths: {
    "/api/v1/auth/register": { post: { ...operation("Create a candidate or recruiter account"), tags: ["Auth"], requestBody: jsonBody } },
    "/api/v1/auth/login": { post: { ...operation("Sign in and issue access and refresh tokens"), tags: ["Auth"], requestBody: jsonBody } },
    "/api/v1/auth/refresh": { post: { ...operation("Rotate the refresh token"), tags: ["Auth"] } },
    "/api/v1/auth/logout": { post: { ...operation("Revoke the current session", true), tags: ["Auth"] } },
    "/api/v1/companies/directory": { get: { ...operation("List public companies"), tags: ["Companies"] } },
    "/api/v1/companies/directory/{slug}": { get: { ...operation("Get a public company and its active jobs"), tags: ["Companies"], parameters: [{ name: "slug", in: "path", required: true, schema: { type: "string" } }] } },
    "/api/v1/companies/me": { get: { ...operation("Get the current user's company", true), tags: ["Companies"] } },
    "/api/v1/companies": { post: { ...operation("Create a company", true), tags: ["Companies"], requestBody: jsonBody } },
    "/api/v1/companies/{companyId}": { patch: { ...operation("Update a company", true), tags: ["Companies"], parameters: [pathParam("companyId")], requestBody: jsonBody }, delete: { ...operation("Soft-delete a company and archive its jobs", true), tags: ["Companies"], parameters: [pathParam("companyId")] } },
    "/api/v1/profiles/me": { get: { ...operation("Get the current user's profile", true), tags: ["Profiles"] }, patch: { ...operation("Update the current user's profile", true), tags: ["Profiles"], requestBody: jsonBody } },
    "/api/v1/profiles/{userId}": { get: { ...operation("Get a public candidate profile", true), tags: ["Profiles"], parameters: [pathParam("userId")] } },
    ...Object.fromEntries(["educations", "experiences", "certifications", "projects"].map((item) => [`/api/v1/profiles/me/${item}`, { post: { ...operation(`Add a profile ${item.slice(0, -1)}`, true), tags: ["Profiles"], requestBody: jsonBody } }])),
    ...Object.fromEntries(["educations", "experiences", "certifications", "projects"].map((item) => [`/api/v1/profiles/me/${item}/{id}`, { delete: { ...operation(`Delete a profile ${item.slice(0, -1)}`, true), tags: ["Profiles"], parameters: [pathParam("id")] } }])),
    "/api/v1/jobs": { get: { ...operation("Search and filter active jobs"), tags: ["Jobs"], parameters: ["q", "location", "workplaceType", "employmentType", "experienceLevel", "cursor", "limit"].map((name) => ({ name, in: "query", required: false, schema: { type: "string" } })) }, post: { ...operation("Create a job", true), tags: ["Jobs"], requestBody: jsonBody } },
    "/api/v1/jobs/{id}": { get: { ...operation("Get an active job posting"), tags: ["Jobs"], parameters: [pathParam("id")] }, patch: { ...operation("Edit a managed job or move it through its lifecycle", true), tags: ["Jobs"], parameters: [pathParam("id")], requestBody: jsonBody } },
    "/api/v1/jobs/mine": { get: { ...operation("List jobs managed by the current recruiter", true), tags: ["Jobs"] } },
    "/api/v1/jobs/saved/me": { get: { ...operation("List saved jobs", true), tags: ["Jobs"] } },
    "/api/v1/jobs/{id}/save": { post: { ...operation("Save a job", true), tags: ["Jobs"], parameters: [pathParam("id")] }, delete: { ...operation("Unsave a job", true), tags: ["Jobs"], parameters: [pathParam("id")] } },
    "/api/v1/applications": { post: { ...operation("Apply to an active job", true), tags: ["Applications"], requestBody: jsonBody } },
    "/api/v1/applications/me": { get: { ...operation("List the current candidate's applications", true), tags: ["Applications"] } },
    "/api/v1/jobs/{jobId}/applications": { get: { ...operation("List applicants for a managed job", true), tags: ["Applications"], parameters: [pathParam("jobId")] } },
    "/api/v1/applications/{id}/status": { patch: { ...operation("Move an application through the hiring pipeline", true), tags: ["Applications"], parameters: [pathParam("id")], requestBody: jsonBody } },
    "/api/v1/applications/{id}/withdraw": { patch: { ...operation("Withdraw an application", true), tags: ["Applications"], parameters: [pathParam("id")] } },
    "/api/v1/applications/{id}/notes": { post: { ...operation("Add a recruiter note", true), tags: ["Applications"], parameters: [pathParam("id")], requestBody: jsonBody } },
    "/api/v1/applications/{id}/interviews": { post: { ...operation("Schedule an interview", true), tags: ["Interviews"], parameters: [pathParam("id")], requestBody: jsonBody } },
    "/api/v1/interviews/me": { get: { ...operation("List the current user's interviews", true), tags: ["Interviews"] } },
    "/api/v1/interviews/{id}/cancel": { patch: { ...operation("Cancel an interview", true), tags: ["Interviews"], parameters: [pathParam("id")] } },
    "/api/v1/notifications/me": { get: { ...operation("List notifications", true), tags: ["Notifications"] } },
    "/api/v1/notifications/{id}/read": { patch: { ...operation("Mark a notification as read", true), tags: ["Notifications"], parameters: [pathParam("id")] } },
    "/api/v1/notifications/read-all": { patch: { ...operation("Mark all notifications as read", true), tags: ["Notifications"] } },
    "/api/v1/admin/overview": { get: { ...operation("Get platform analytics", true), tags: ["Admin"] } },
    "/api/v1/admin/users": { get: { ...operation("List platform users", true), tags: ["Admin"] } },
    "/api/v1/admin/users/{id}/status": { patch: { ...operation("Change a user's platform status", true), tags: ["Admin"], parameters: [pathParam("id")], requestBody: jsonBody } },
    "/api/v1/admin/companies": { get: { ...operation("List companies for moderation", true), tags: ["Admin"] } },
    "/api/v1/admin/companies/{id}/verification": { patch: { ...operation("Verify or unverify a company", true), tags: ["Admin"], parameters: [pathParam("id")], requestBody: jsonBody } },
    "/api/v1/admin/audit-logs": { get: { ...operation("List audit events", true), tags: ["Admin"] } },
    "/api/v1/uploads/presigned-url": { post: { ...operation("Request a direct-to-object-storage upload URL", true), tags: ["Uploads"], requestBody: jsonBody } },
    "/api/v1/uploads/complete": { post: { ...operation("Register a completed resume upload", true), tags: ["Uploads"], requestBody: jsonBody } },
    "/api/v1/uploads/resumes/{resumeId}/primary": { patch: { ...operation("Set a resume as primary", true), tags: ["Uploads"], parameters: [pathParam("resumeId")] } },
    "/api/v1/uploads/resumes/{resumeId}": { delete: { ...operation("Delete a resume", true), tags: ["Uploads"], parameters: [pathParam("resumeId")] } },
    "/api/v1/uploads/resumes/{resumeId}/download-url": { get: { ...operation("Create an authorized resume download URL", true), tags: ["Uploads"], parameters: [pathParam("resumeId")] } },
  },
} as const;
