"use client";

import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import { Activity, Building2, Check, ShieldAlert, UsersRound, BriefcaseBusiness } from "lucide-react";
import { useState } from "react";
import { apiFetch, ApiRequestError } from "@/lib/api";
import { DashboardShell } from "@/components/dashboard-shell";

type Overview = { users: number; candidates: number; recruiters: number; companies: number; activeJobs: number; applications: number; applicationFunnel: Record<string, number> };
type AdminUser = { id: string; email: string; firstName: string; lastName: string; status: string; isVerified: boolean; createdAt: string; roles: Array<{ role: { name: string } }> };
type Company = { id: string; name: string; industry: string | null; isVerified: boolean; _count: { jobs: number; members: number } };

export default function AdminDashboardPage() {
  const [tab, setTab] = useState<"overview" | "users" | "companies" | "audit">("overview");
  const client = useQueryClient();
  const overview = useQuery({ queryKey: ["admin-overview"], queryFn: () => apiFetch<{ data: Overview }>("/admin/overview") });
  const users = useQuery({ queryKey: ["admin-users"], queryFn: () => apiFetch<{ data: AdminUser[] }>("/admin/users?limit=50"), enabled: tab === "users" });
  const companies = useQuery({ queryKey: ["admin-companies"], queryFn: () => apiFetch<{ data: Company[] }>("/admin/companies"), enabled: tab === "companies" });
  const audit = useQuery({ queryKey: ["admin-audit"], queryFn: () => apiFetch<{ data: Array<{ id: string; action: string; entityName: string; createdAt: string; actor: { email: string } | null }> }>("/admin/audit-logs?limit=30"), enabled: tab === "audit" });
  const moderation = useMutation({
    mutationFn: ({ id, status }: { id: string; status: string }) => apiFetch(`/admin/users/${id}/status`, { method: "PATCH", body: JSON.stringify({ status }) }),
    onSuccess: () => { void client.invalidateQueries({ queryKey: ["admin-users"] }); void client.invalidateQueries({ queryKey: ["admin-overview"] }); },
  });
  const verify = useMutation({
    mutationFn: ({ id, isVerified }: { id: string; isVerified: boolean }) => apiFetch(`/admin/companies/${id}/verification`, { method: "PATCH", body: JSON.stringify({ isVerified }) }),
    onSuccess: () => { void client.invalidateQueries({ queryKey: ["admin-companies"] }); void client.invalidateQueries({ queryKey: ["admin-overview"] }); },
  });
  const stats = overview.data?.data;
  return <DashboardShell audience="admin"><div><p className="eyebrow">A clear view of the platform</p><h1 className="mt-2 font-display text-3xl font-bold tracking-[-.05em]">Admin dashboard</h1><p className="mt-2 text-sm text-muted">Keep the marketplace healthy, welcoming, and useful.</p></div>
    <div className="mt-7 flex flex-wrap gap-2 border-b border-black/[.08] pb-3">{(["overview", "users", "companies", "audit"] as const).map((item) => <button key={item} onClick={() => setTab(item)} className={`rounded-lg px-4 py-2 text-xs font-bold capitalize ${tab === item ? "bg-brand text-white" : "text-muted hover:bg-white"}`}>{item === "audit" ? "Audit log" : item}</button>)}</div>
    {tab === "overview" && <><div className="mt-6 grid gap-3 sm:grid-cols-2 xl:grid-cols-4"><Metric icon={UsersRound} label="All users" value={stats?.users} /><Metric icon={UsersRound} label="Candidates" value={stats?.candidates} /><Metric icon={Building2} label="Companies" value={stats?.companies} /><Metric icon={BriefcaseBusiness} label="Active roles" value={stats?.activeJobs} /></div><div className="mt-6 grid gap-4 lg:grid-cols-2"><div className="card p-5"><p className="eyebrow">Marketplace health</p><h2 className="mt-2 font-display text-xl font-bold">The people behind the platform</h2><div className="mt-5 grid grid-cols-2 gap-3"><div className="rounded-xl bg-canvas p-4"><p className="text-xs text-muted">Hiring teams</p><p className="mt-1 text-2xl font-bold">{stats?.recruiters ?? "—"}</p></div><div className="rounded-xl bg-canvas p-4"><p className="text-xs text-muted">Applications</p><p className="mt-1 text-2xl font-bold">{stats?.applications ?? "—"}</p></div></div></div><div className="card p-5"><p className="eyebrow">Application funnel</p><h2 className="mt-2 font-display text-xl font-bold">Where candidates are</h2><div className="mt-4 space-y-3">{Object.entries(stats?.applicationFunnel ?? {}).map(([status, count]) => <div key={status}><div className="mb-1 flex justify-between text-xs"><span className="font-medium">{status.replaceAll("_", " ")}</span><span className="text-muted">{count}</span></div><div className="h-2 overflow-hidden rounded-full bg-canvas"><div className="h-full rounded-full bg-brand" style={{ width: `${stats?.applications ? Math.max(4, count / stats.applications * 100) : 0}%` }} /></div></div>)}</div></div></div></>}
    {tab === "users" && <div className="card mt-6 overflow-hidden"><div className="border-b border-black/[.06] p-5"><h2 className="font-display text-lg font-bold">People on TalentSpring</h2><p className="mt-1 text-xs text-muted">Suspend accounts that violate platform guidelines.</p></div><div className="divide-y divide-black/[.06]">{users.data?.data.map((user) => <div key={user.id} className="flex flex-col justify-between gap-3 p-4 sm:flex-row sm:items-center"><div><p className="text-sm font-semibold">{user.firstName} {user.lastName} <span className="ml-2 rounded-full bg-canvas px-2 py-1 text-[9px] font-bold uppercase tracking-wide text-muted">{user.roles.map(({ role }) => role.name).join(", ")}</span></p><p className="mt-1 text-xs text-muted">{user.email} · Joined {new Date(user.createdAt).toLocaleDateString()}</p></div><div className="flex items-center gap-2"><span className="tag">{user.status}</span><button onClick={() => moderation.mutate({ id: user.id, status: user.status === "SUSPENDED" ? "ACTIVE" : "SUSPENDED" })} className="rounded-lg border border-black/10 px-3 py-2 text-xs font-semibold hover:border-brand/30">{user.status === "SUSPENDED" ? "Restore account" : "Suspend"}</button></div></div>)}</div></div>}
    {tab === "companies" && <div className="mt-6 space-y-3">{companies.data?.data.map((company) => <div key={company.id} className="flex flex-col justify-between gap-3 rounded-2xl border border-black/[.06] bg-white p-5 sm:flex-row sm:items-center"><div><p className="font-display font-bold">{company.name}</p><p className="mt-1 text-xs text-muted">{company.industry ?? "Industry not listed"} · {company._count.jobs} jobs · {company._count.members} members</p></div><button onClick={() => verify.mutate({ id: company.id, isVerified: !company.isVerified })} className={`inline-flex items-center gap-2 rounded-lg px-3 py-2 text-xs font-bold ${company.isVerified ? "bg-brand-soft text-brand" : "bg-accent text-ink"}`}>{company.isVerified ? <><Check size={14} /> Verified · remove</> : <><ShieldAlert size={14} /> Verify company</>}</button></div>)}</div>}
    {tab === "audit" && <div className="card mt-6 divide-y divide-black/[.06]">{audit.data?.data.map((entry) => <div key={entry.id} className="flex flex-col justify-between gap-2 p-4 sm:flex-row"><div><p className="text-sm font-semibold">{entry.action.replaceAll("_", " ").toLowerCase()}</p><p className="mt-1 text-xs text-muted">{entry.entityName} · {entry.actor?.email ?? "System"}</p></div><time className="text-xs text-muted">{new Date(entry.createdAt).toLocaleString()}</time></div>)}</div>}
    {(moderation.isError || verify.isError) && <p role="alert" className="mt-4 rounded-xl bg-rose-50 p-3 text-sm text-rose-700">{(moderation.error ?? verify.error) instanceof ApiRequestError ? (moderation.error ?? verify.error)?.message : "The moderation action could not be completed."}</p>}
  </DashboardShell>;
}

function Metric({ icon: Icon, label, value }: { icon: typeof UsersRound; label: string; value?: number }) { return <div className="card p-4"><div className="flex items-center justify-between"><p className="text-xs font-semibold text-muted">{label}</p><Icon size={16} className="text-brand" /></div><p className="mt-2 font-display text-3xl font-bold">{value ?? "—"}</p></div>; }
